### ISSUE TITLE
login() missing 1 required positional argument: 'email'

### ISSUE THREAD

**Issue by ManPython** [dkarchmer/django-rest-framework-client#4]
We need always `ok = c.login(email=email, password=password)`?
Want just `ok = c.login(token = asdfasfasfasfasdfad)` - is possible to easy manage this or implement with this way?

**Comment by ManPython** [comment]
BTW login in DRF is most often by username not email

**Comment by dkarchmer** [comment]
Finally using this myself on a new server that uses username instead of email, and yes, this needs to be enhanced. But the workaround is to derive 

```
from drf_client.connection import Api as RestApi

class NewServerApi(RestApi):

    def username_login(self, password, username):
        assert('LOGIN' in self.options)
        data = {'username': username, 'password': password}
        url = '{0}/{1}'.format(self.base_url, self.options['LOGIN'])

        payload = json.dumps(data)
        r = requests.post(url, data=payload, headers=DEFAULT_HEADERS)
        if r.status_code in [200, 201]:
            content = json.loads(r.content.decode())
            self.token = content['token']
            self.username = username
            return True
        
        return False
```

**Comment by dkarchmer** [comment]
The changes to not require email anymore were implemented in https://github.com/dkarchmer/django-rest-framework-client/pull/5/files

For setting the token, you can already do this with `set_token` (you do not need to always `c.login()`

```
c.set_token(token)
```
